name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas requests xlwt pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile binance_volume.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binance-exe
          path: dist/binance_volume.exe
